// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXhcini8nc4iWsHzwCsqqgpb36KRQ-fu4',
    appId: '1:945407682435:web:feadb34b8f07f07758b8b6',
    messagingSenderId: '945407682435',
    projectId: 'student-record-ishan',
    authDomain: 'student-record-ishan.firebaseapp.com',
    storageBucket: 'student-record-ishan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaanU8a_reaRJl_7R-dQgysl5lA8vzmS8',
    appId: '1:945407682435:android:f2c9033328df7e2958b8b6',
    messagingSenderId: '945407682435',
    projectId: 'student-record-ishan',
    storageBucket: 'student-record-ishan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5N4BRBbyF7c4vQkfKsvQhGDuNQYSoiIA',
    appId: '1:945407682435:ios:a7c7d5fd74920ab958b8b6',
    messagingSenderId: '945407682435',
    projectId: 'student-record-ishan',
    storageBucket: 'student-record-ishan.firebasestorage.app',
    iosBundleId: 'com.example.teamnougatStudentRecordManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5N4BRBbyF7c4vQkfKsvQhGDuNQYSoiIA',
    appId: '1:945407682435:ios:a7c7d5fd74920ab958b8b6',
    messagingSenderId: '945407682435',
    projectId: 'student-record-ishan',
    storageBucket: 'student-record-ishan.firebasestorage.app',
    iosBundleId: 'com.example.teamnougatStudentRecordManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXhcini8nc4iWsHzwCsqqgpb36KRQ-fu4',
    appId: '1:945407682435:web:fb7d00ad6ff2924758b8b6',
    messagingSenderId: '945407682435',
    projectId: 'student-record-ishan',
    authDomain: 'student-record-ishan.firebaseapp.com',
    storageBucket: 'student-record-ishan.firebasestorage.app',
  );
}
